name: Include Twinlibs.md in README.md

on:
  push:
     branches:
        - main
        - stable
  pull_request:
    types: [open, synchronize]

jobs:
  build:
     name: Include Twinlibs.md
     runs-on: ubuntu-latest
     steps:
        - name: Checkout source code
          uses: actions/checkout@v3
        - run: git config --system --add safe.directory /home/runner/work/Twinlibs/Twinlibs
        - run: sed -i '/<!-- TWINLIBS_MD:START -->/,/<!-- TWINLIBS_MD:END -->/d' README.md
        - run: echo '<!-- TWINLIBS_MD:START -->' >> README.md
        - run: cat Twinlibs.md >> README.md
        - run: echo '<!-- TWINLIBS_MD:END -->' >> README.md

        - name: push
          uses: actions-x/commit@v3
          env:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
             name: GitHub Actions Autocommitter
             files: ./README.md
             message: 'ci: updated README'
